'use client';

import { useLocale } from 'next-intl';

/**
 * UI copy for rig duels and squads.
 *
 * `en` is deliberately NOT `as const` — widening the values to `string` is
 * what lets `zh` and `ko` be typed as `Copy`, so TypeScript fails the build
 * on a key that was added to one locale and forgotten in another.
 */
const en = {
  DUELS: {
    eyebrow: 'Rig vs rig',
    title: 'Rig Duels',
    subtitle:
      'Put your build up against another miner for 24 hours. Higher output wins; the loser forfeits a slice of what they mined.',
    back: 'Dashboard',
    offline: 'Could not reach the grid. Try again in a moment.',
    heroEyebrow: 'How a duel works',
    heroTitle: 'Twenty-four hours. Two rigs. One winner.',
    heroBody:
      'Create a duel and share the link. When someone accepts, both rigs race for 24 hours. Whoever mines more VOLTS in the window wins, and the loser hands over a stake of their in-window earnings.',
    point1Title: 'Same clock',
    point1Body:
      'The window starts the moment your opponent accepts. Mine, keep the grid stable, and let the rig do the rest.',
    point2Title: '10% stake',
    point2Body:
      'The loser forfeits 10% of the VOLTS they mined during the duel. Never more than they earned.',
    point3Title: 'Share to challenge',
    point3Body:
      'Post the link anywhere. A miner without an account can sign up and accept in one step.',
    create: 'Create duel',
    creating: 'Creating…',
    openEyebrow: 'Open challenge',
    openTitle: 'Waiting for an opponent',
    openBody:
      'Share this link. The first miner to accept starts the clock. Open duels expire after 48 hours.',
    link: 'Duel link',
    copy: 'Copy link',
    copied: 'Copied',
    share: 'Share',
    shareX: 'Post on X',
    shareTelegram: 'Telegram',
    shareWhatsApp: 'WhatsApp',
    shareText: (rate: string) =>
      `My rig is making ${rate} VOLTS/h on VOLTARA. Think yours can beat it? 24h duel, 10% stake:`,
    cancel: 'Cancel duel',
    activeEyebrow: 'Live duel',
    activeTitle: 'Race in progress',
    you: 'You',
    vs: 'VS',
    leading: 'Leading',
    trailing: 'Trailing',
    tied: 'Tied',
    endsIn: 'Ends in',
    mined: 'VOLTS mined',
    rate: 'VOLTS / h',
    stability: 'Stability',
    historyTitle: 'Past duels',
    historyEmpty: 'No duels yet. Your record starts with the first one.',
    won: 'Won',
    lost: 'Lost',
    draw: 'Draw',
    expired: 'Expired',
    cancelled: 'Cancelled',
    transferred: (pts: string) => `${pts} VOLTS`,
    opponentUnknown: 'Opponent',
  },

  DUEL_LANDING: {
    eyebrow: 'You have been challenged',
    title: (name: string) => `${name} wants a duel`,
    body: 'Accept and both rigs race for 24 hours. Whoever mines more VOLTS wins; the loser forfeits 10% of what they mined in the window.',
    accept: 'Accept duel',
    accepting: 'Accepting…',
    signUpToAccept: 'Sign up to accept',
    signInHint: 'Free to join. Your rig starts mining the moment you sign up.',
    challengerRig: "Challenger's rig",
    yours: 'This is your own duel. Share the link to find an opponent.',
    goToDuels: 'Go to my duels',
    notFound: 'That duel link is not valid.',
    status: {
      ACTIVE: 'This duel is already running.',
      SETTLED: 'This duel has been settled.',
      CANCELLED: 'The challenger cancelled this duel.',
      EXPIRED: 'Nobody accepted in time, so this duel expired.',
    } as Record<string, string>,
    winner: 'Winner',
    noWinner: 'Draw — nothing changed hands',
    stakeLabel: 'Stake',
    windowLabel: 'Window',
    windowValue: '24 hours',
    learn: 'What is VOLTARA?',
  },

  SQUAD: {
    eyebrow: 'Pooled grid',
    title: 'Squad',
    subtitle:
      'Up to five miners pooling spare cooling and power. Your headroom keeps a teammate stable; theirs keeps you.',
    back: 'Dashboard',
    offline: 'Could not reach the grid. Try again in a moment.',
    createTitle: 'Start a squad',
    createBody: 'Name it, then share the code with up to four miners.',
    namePlaceholder: 'Squad name',
    create: 'Create squad',
    joinTitle: 'Join a squad',
    joinBody: 'Paste the code a squad owner shared with you.',
    codePlaceholder: 'Squad code',
    join: 'Join',
    working: 'Working…',
    code: 'Invite code',
    copy: 'Copy code',
    copied: 'Copied',
    share: 'Share',
    shareText: (name: string) =>
      `Join my squad "${name}" on VOLTARA — we pool cooling and power so every rig stays at 100%. Code:`,
    leave: 'Leave squad',
    leaveConfirm: 'Leave this squad? Your rig loses any pooled cooling or power immediately.',
    owner: 'Owner',
    members: 'Members',
    poolEyebrow: 'Shared headroom',
    poolTitle: 'The pool',
    poolBody: 'Unused cooling and power from every member, lent to whoever is over budget.',
    cooling: 'Cooling',
    power: 'Power',
    lent: 'lent',
    spare: 'spare',
    unit: { cooling: 'TU', power: 'W' },
    earned7d: 'Mined by the squad, 7 days',
    memberRate: 'VOLTS / h',
    memberStability: 'Stability',
    receiving: 'Receiving',
    giving: 'Spare',
    boardTitle: 'Squad rankings',
    boardBody: 'VOLTS mined by all members in the last 7 days.',
    rank: '#',
    squadCol: 'Squad',
    membersCol: 'Members',
    earnedCol: '7-day VOLTS',
    yours: 'Yours',
    boardEmpty: 'No squads on the board yet.',
    full: (n: number, max: number) => `${n} / ${max} members`,
  },

  LEADERBOARD_LINKS: {
    duelsTitle: 'Rig Duels',
    duelsBody: '24h race, 10% stake. Challenge a miner.',
    squadTitle: 'Squads',
    squadBody: 'Pool cooling and power with four others.',
    open: 'Open',
  },

  SEASON: {
    eyebrow: 'This season',
    title: 'Weekly season',
    body: 'Opens Monday 00:00 UTC and settles the following Monday. The top ten miners are paid in VOLTS.',
    pool: 'Prize pool',
    closesIn: 'Closes in',
    closed: 'Settled',
    place: 'Place',
    earned: 'Mined this week',
    prize: 'Prize',
    projected: 'Projected',
    you: 'You',
    yourPlace: 'Your place',
    unranked: 'Not ranked yet',
    unrankedHint: 'Mine any VOLTS this week and you join the table.',
    outOf: (n: number) => `of ${n} miners`,
    prizeIfHolds: 'If you hold this place',
    noPrizeYet: 'Reach the top ten to win a prize',
    empty: 'Nobody has mined this season yet.',
    lastSeason: 'Last season',
    lastSeasonBody: (key: string) => `${key} final standings — paid out.`,
    youWon: (volts: number) => `You won ${volts} VOLTS`,
    volts: 'VOLTS',
    watch: 'Watch rig',
  },

  WATCH: {
    eyebrow: 'Spectating',
    title: 'Watching a rig',
    subtitle: 'Live from the grid. This build updates every ten seconds.',
    offline: 'Could not reach that rig.',
    notFound: 'No rig behind that link. It may have been retired.',
    loading: 'Tuning in…',
    stability: 'Grid stability',
    rate: 'Output',
    perHour: 'VOLTS / h',
    parts: 'Parts running',
    streak: 'Streak',
    days: 'days',
    joined: 'Mining since',
    thermal: 'Heat vs cooling',
    power: 'Draw vs supply',
    overclocking: 'Overclocking',
    hot: 'Running hot',
    burned: 'Burned',
    empty: 'Empty socket',
    eventLive: 'Grid event',
    challenge: 'Challenge this rig',
    signUpToChallenge: 'Sign up to challenge',
    backToBoard: 'Leaderboard',
    watchCta: 'Watch',
    ownRig: 'This is your rig',
    goToMine: 'Open my rig',
  },

  APPRENTICE: {
    eyebrow: 'Mentorship',
    title: 'Apprentices',
    subtitle:
      'Adopt a newcomer. Hand over a spare part, and earn a share of what they mine — minted on top, never taken from them.',
    back: 'Dashboard',
    offline: 'Could not reach the grid. Try again in a moment.',
    heroTitle: 'Teach someone to hold the grid',
    heroBody:
      'A mentor keeps 5% of what their apprentice mines for the first 30 days. That share is newly minted, so being mentored costs a newcomer nothing.',
    pointTeachTitle: 'Give what you are not running',
    pointTeachBody:
      'Spare parts sitting in your inventory earn nothing. Hand one to an apprentice and it goes straight into their rig.',
    pointEarnTitle: '5% for 30 days',
    pointEarnBody:
      'Credited to you on every claim they make, on top of theirs. It expires, so mentoring is a push, not a pension.',
    pointCapTitle: 'Three at a time',
    pointCapBody:
      'A mentor can hold three apprenticeships at once, and must be holding 100% stability to take on another.',
    offerTitle: 'Take on an apprentice',
    offerHint: 'Paste their invite code. They have to accept before anything starts.',
    offerPlaceholder: 'Invite code',
    offerCta: 'Send offer',
    offerSent: 'Offer sent. Waiting on them to accept.',
    cannotMentor: 'You cannot take on an apprentice yet',
    blockTooNew: (n: number) => `Mentoring opens after your first week. ${n} day(s) to go.`,
    blockUnstable: 'Your rig has to be holding 100% stability first.',
    blockCapacity: 'You already have as many apprentices as you can hold.',
    blockIsApprentice: 'You cannot mentor while you are being mentored.',
    invitesTitle: 'You have been offered a mentor',
    invitesBody: 'They keep a 5% share of what you mine for 30 days. It costs you nothing.',
    accept: 'Accept',
    decline: 'Decline',
    pendingTitle: 'Waiting to be accepted',
    activeTitle: 'Your apprentices',
    activeEmpty: 'No apprentices yet.',
    myMentorTitle: 'Your mentor',
    noMentor: 'You have no mentor.',
    end: 'End',
    endConfirm: 'End this apprenticeship? It cannot be restarted with the same miner.',
    gift: 'Gift a part',
    giftTitle: 'Gift a part',
    giftHint: 'Only parts that are not installed can be handed over.',
    giftEmpty: 'Nothing spare in your inventory.',
    giftCta: 'Hand it over',
    gifted: 'Sent. It went straight into their rig.',
    earned: 'Earned as a mentor',
    cutEnds: 'Share ends',
    cutEnded: 'Share has ended',
    stability: 'Stability',
    rate: 'Output',
    watch: 'Watch rig',
    joined: 'Joined',
    roleMentor: 'You mentor them',
    roleApprentice: 'They mentor you',
  },
};

type Copy = typeof en;

const zh: Copy = {
  DUELS: {
    eyebrow: '矿机对决',
    title: '矿机对决',
    subtitle:
      '让你的配置与另一位矿工对拼 24 小时。产出高者获胜，落败方交出所挖 VOLTS 的一部分。',
    back: '控制台',
    offline: '无法连接电网，请稍后重试。',
    heroEyebrow: '对决规则',
    heroTitle: '二十四小时。两台矿机。一个赢家。',
    heroBody:
      '创建对决并分享链接。有人接受后，两台矿机开始 24 小时竞速。窗口期内挖到更多 VOLTS 的一方获胜，落败方交出该期间收益的一部分作为赌注。',
    point1Title: '同一时钟',
    point1Body: '对手接受的瞬间开始计时。挖矿、保持电网稳定，其余交给矿机。',
    point2Title: '10% 赌注',
    point2Body: '落败方交出对决期间所挖 VOLTS 的 10%，绝不超过其收益。',
    point3Title: '分享即挑战',
    point3Body: '把链接发到任何地方。没有账号的矿工也能一步注册并接受挑战。',
    create: '创建对决',
    creating: '创建中…',
    openEyebrow: '待接受的挑战',
    openTitle: '等待对手',
    openBody: '分享此链接。第一位接受的矿工将启动计时。未被接受的对决 48 小时后过期。',
    link: '对决链接',
    copy: '复制链接',
    copied: '已复制',
    share: '分享',
    shareX: '发布到 X',
    shareTelegram: 'Telegram',
    shareWhatsApp: 'WhatsApp',
    shareText: (rate: string) =>
      `我的矿机在 VOLTARA 上每小时产出 ${rate} VOLTS。你的能超过吗？24 小时对决，10% 赌注：`,
    cancel: '取消对决',
    activeEyebrow: '进行中的对决',
    activeTitle: '竞速进行中',
    you: '你',
    vs: 'VS',
    leading: '领先',
    trailing: '落后',
    tied: '平局',
    endsIn: '剩余',
    mined: '已挖 VOLTS',
    rate: 'VOLTS / h',
    stability: '稳定度',
    historyTitle: '历史对决',
    historyEmpty: '还没有对决。第一场就是你战绩的开始。',
    won: '胜',
    lost: '负',
    draw: '平',
    expired: '已过期',
    cancelled: '已取消',
    transferred: (pts: string) => `${pts} VOLTS`,
    opponentUnknown: '对手',
  },

  DUEL_LANDING: {
    eyebrow: '有人向你发起挑战',
    title: (name: string) => `${name} 向你发起对决`,
    body: '接受后，两台矿机竞速 24 小时。挖到更多 VOLTS 的一方获胜，落败方交出该期间收益的 10%。',
    accept: '接受对决',
    accepting: '接受中…',
    signUpToAccept: '注册以接受挑战',
    signInHint: '免费加入。注册后你的矿机立即开始挖矿。',
    challengerRig: '挑战者的矿机',
    yours: '这是你自己的对决。分享链接来寻找对手。',
    goToDuels: '前往我的对决',
    notFound: '该对决链接无效。',
    status: {
      ACTIVE: '该对决已经开始。',
      SETTLED: '该对决已结算。',
      CANCELLED: '挑战者已取消该对决。',
      EXPIRED: '无人及时接受，该对决已过期。',
    } as Record<string, string>,
    winner: '获胜方',
    noWinner: '平局 — 无任何转移',
    stakeLabel: '赌注',
    windowLabel: '窗口期',
    windowValue: '24 小时',
    learn: 'VOLTARA 是什么？',
  },

  SQUAD: {
    eyebrow: '共享电网',
    title: '战队',
    subtitle:
      '最多五位矿工共享富余的散热与供电。你的余量让队友保持稳定，他们的余量也支撑着你。',
    back: '控制台',
    offline: '无法连接电网，请稍后重试。',
    createTitle: '创建战队',
    createBody: '取个名字，然后把邀请码分享给最多四位矿工。',
    namePlaceholder: '战队名称',
    create: '创建战队',
    joinTitle: '加入战队',
    joinBody: '粘贴队长分享给你的邀请码。',
    codePlaceholder: '战队邀请码',
    join: '加入',
    working: '处理中…',
    code: '邀请码',
    copy: '复制邀请码',
    copied: '已复制',
    share: '分享',
    shareText: (name: string) =>
      `加入我在 VOLTARA 的战队「${name}」— 我们共享散热与供电，让每台矿机都保持 100%。邀请码：`,
    leave: '退出战队',
    leaveConfirm: '确定退出战队？你的矿机将立即失去共享的散热与供电。',
    owner: '队长',
    members: '成员',
    poolEyebrow: '共享余量',
    poolTitle: '共享池',
    poolBody: '汇集所有成员未使用的散热与供电，借给超出预算的队员。',
    cooling: '散热',
    power: '供电',
    lent: '已借出',
    spare: '富余',
    unit: { cooling: 'TU', power: 'W' },
    earned7d: '战队 7 天挖矿总量',
    memberRate: 'VOLTS / h',
    memberStability: '稳定度',
    receiving: '获得',
    giving: '富余',
    boardTitle: '战队排行榜',
    boardBody: '全体成员近 7 天挖到的 VOLTS。',
    rank: '#',
    squadCol: '战队',
    membersCol: '成员',
    earnedCol: '7 天 VOLTS',
    yours: '你的',
    boardEmpty: '排行榜上还没有战队。',
    full: (n: number, max: number) => `${n} / ${max} 名成员`,
  },

  LEADERBOARD_LINKS: {
    duelsTitle: '矿机对决',
    duelsBody: '24 小时竞速，10% 赌注。向矿工发起挑战。',
    squadTitle: '战队',
    squadBody: '与另外四人共享散热与供电。',
    open: '打开',
  },

  SEASON: {
    eyebrow: '本赛季',
    title: '每周赛季',
    body: '每周一 00:00 UTC 开始，下周一结算。前十名矿工可获得 VOLTS。',
    pool: '奖池',
    closesIn: '距结算',
    closed: '已结算',
    place: '名次',
    earned: '本周产出',
    prize: '奖励',
    projected: '预计',
    you: '你',
    yourPlace: '你的名次',
    unranked: '尚未上榜',
    unrankedHint: '本周挖到 VOLTS 即可进入排行。',
    outOf: (n: number) => `共 ${n} 名矿工`,
    prizeIfHolds: '若保持当前名次',
    noPrizeYet: '进入前十即可获得奖励',
    empty: '本赛季还没有人开始挖矿。',
    lastSeason: '上个赛季',
    lastSeasonBody: (key: string) => `${key} 最终结果 — 奖励已发放。`,
    youWon: (volts: number) => `你赢得了 ${volts} VOLTS`,
    volts: 'VOLTS',
    watch: '观看矿机',
  },

  WATCH: {
    eyebrow: '观战中',
    title: '正在观看一台矿机',
    subtitle: '来自电网的实时画面，每十秒更新一次。',
    offline: '无法连接到这台矿机。',
    notFound: '该链接背后没有矿机，可能已经退役。',
    loading: '正在接入…',
    stability: '电网稳定度',
    rate: '产出',
    perHour: 'VOLTS / h',
    parts: '运行中的部件',
    streak: '连续天数',
    days: '天',
    joined: '开始挖矿于',
    thermal: '热量与散热',
    power: '功耗与供电',
    overclocking: '超频中',
    hot: '过热运行',
    burned: '已烧毁',
    empty: '空插槽',
    eventLive: '电网事件',
    challenge: '向这台矿机挑战',
    signUpToChallenge: '注册后即可挑战',
    backToBoard: '排行榜',
    watchCta: '观看',
    ownRig: '这是你的矿机',
    goToMine: '打开我的矿机',
  },

  APPRENTICE: {
    eyebrow: '师徒',
    title: '学徒',
    subtitle:
      '收一位新人为徒。把闲置部件交给他，并分享他挖到的一部分产出——这部分是额外增发的，绝不从他那里扣除。',
    back: '控制台',
    offline: '无法连接电网，请稍后再试。',
    heroTitle: '教会别人稳住电网',
    heroBody:
      '师父可获得徒弟前 30 天挖矿产出的 5%。这笔份额是额外增发的，所以拜师对新人来说完全免费。',
    pointTeachTitle: '把闲置的部件送出去',
    pointTeachBody: '躺在仓库里的部件不产生任何收益。交给徒弟，它会直接装进他的矿机。',
    pointEarnTitle: '30 天内 5%',
    pointEarnBody: '他每次结算，你都会额外获得一份。份额会到期，所以师徒是一次助推，不是长期收租。',
    pointCapTitle: '同时最多三位',
    pointCapBody: '一位师父最多同时带三位徒弟，并且必须保持 100% 稳定度才能再收一位。',
    offerTitle: '收一位学徒',
    offerHint: '粘贴他的邀请码。需要对方接受后才会生效。',
    offerPlaceholder: '邀请码',
    offerCta: '发送邀请',
    offerSent: '邀请已发送，等待对方接受。',
    cannotMentor: '你目前还不能收学徒',
    blockTooNew: (n: number) => `满一周后才能收徒，还差 ${n} 天。`,
    blockUnstable: '你的矿机需要先保持 100% 稳定度。',
    blockCapacity: '你带的学徒已经达到上限。',
    blockIsApprentice: '你自己还在拜师期间，不能收徒。',
    invitesTitle: '有人想收你为徒',
    invitesBody: '他将在 30 天内获得你产出的 5%。这对你没有任何花费。',
    accept: '接受',
    decline: '拒绝',
    pendingTitle: '等待对方接受',
    activeTitle: '你的学徒',
    activeEmpty: '还没有学徒。',
    myMentorTitle: '你的师父',
    noMentor: '你还没有师父。',
    end: '结束',
    endConfirm: '结束这段师徒关系？同一位矿工无法再次建立。',
    gift: '赠送部件',
    giftTitle: '赠送部件',
    giftHint: '只有未装机的部件可以送出。',
    giftEmpty: '仓库里没有闲置部件。',
    giftCta: '送出',
    gifted: '已送出，并直接装进了他的矿机。',
    earned: '作为师父的收益',
    cutEnds: '份额结束于',
    cutEnded: '份额已结束',
    stability: '稳定度',
    rate: '产出',
    watch: '观看矿机',
    joined: '加入于',
    roleMentor: '你是他的师父',
    roleApprentice: '他是你的师父',
  },
};

const ko: Copy = {
  DUELS: {
    eyebrow: '리그 대 리그',
    title: '리그 듀얼',
    subtitle:
      '24시간 동안 다른 채굴자와 리그를 맞붙입니다. 산출량이 높은 쪽이 이기고, 진 쪽은 채굴량의 일부를 내줍니다.',
    back: '대시보드',
    offline: '그리드에 연결할 수 없습니다. 잠시 후 다시 시도하세요.',
    heroEyebrow: '듀얼 규칙',
    heroTitle: '24시간. 두 대의 리그. 한 명의 승자.',
    heroBody:
      '듀얼을 만들고 링크를 공유하세요. 상대가 수락하면 두 리그가 24시간 동안 경쟁합니다. 그 기간에 VOLTS를 더 많이 채굴한 쪽이 이기고, 진 쪽은 기간 수익의 일부를 스테이크로 내놓습니다.',
    point1Title: '같은 시계',
    point1Body:
      '상대가 수락하는 순간 시작됩니다. 채굴하고 그리드 안정도를 지키면 나머지는 리그가 합니다.',
    point2Title: '10% 스테이크',
    point2Body: '진 쪽은 듀얼 기간에 채굴한 VOLTS의 10%를 내줍니다. 번 것보다 더 잃지는 않습니다.',
    point3Title: '공유로 도전장',
    point3Body: '어디든 링크를 올리세요. 계정이 없는 채굴자도 한 번에 가입하고 수락할 수 있습니다.',
    create: '듀얼 만들기',
    creating: '만드는 중…',
    openEyebrow: '공개 도전장',
    openTitle: '상대를 기다리는 중',
    openBody: '이 링크를 공유하세요. 먼저 수락한 채굴자와 시계가 시작됩니다. 공개 듀얼은 48시간 후 만료됩니다.',
    link: '듀얼 링크',
    copy: '링크 복사',
    copied: '복사됨',
    share: '공유',
    shareX: 'X에 게시',
    shareTelegram: 'Telegram',
    shareWhatsApp: 'WhatsApp',
    shareText: (rate: string) =>
      `제 리그는 VOLTARA에서 시간당 ${rate} VOLTS를 만듭니다. 이길 자신 있나요? 24시간 듀얼, 10% 스테이크:`,
    cancel: '듀얼 취소',
    activeEyebrow: '진행 중인 듀얼',
    activeTitle: '경쟁 진행 중',
    you: '나',
    vs: 'VS',
    leading: '앞서는 중',
    trailing: '뒤처지는 중',
    tied: '동점',
    endsIn: '종료까지',
    mined: '채굴한 VOLTS',
    rate: 'VOLTS / h',
    stability: '안정도',
    historyTitle: '지난 듀얼',
    historyEmpty: '아직 듀얼이 없습니다. 첫 판부터 전적이 쌓입니다.',
    won: '승',
    lost: '패',
    draw: '무',
    expired: '만료',
    cancelled: '취소됨',
    transferred: (pts: string) => `${pts} VOLTS`,
    opponentUnknown: '상대',
  },

  DUEL_LANDING: {
    eyebrow: '도전을 받았습니다',
    title: (name: string) => `${name} 님이 듀얼을 신청했습니다`,
    body: '수락하면 두 리그가 24시간 동안 경쟁합니다. VOLTS를 더 많이 채굴한 쪽이 이기고, 진 쪽은 그 기간 채굴량의 10%를 내줍니다.',
    accept: '듀얼 수락',
    accepting: '수락하는 중…',
    signUpToAccept: '가입하고 수락하기',
    signInHint: '가입은 무료. 가입하는 순간 리그가 채굴을 시작합니다.',
    challengerRig: '도전자의 리그',
    yours: '본인이 만든 듀얼입니다. 링크를 공유해 상대를 찾으세요.',
    goToDuels: '내 듀얼로 이동',
    notFound: '유효하지 않은 듀얼 링크입니다.',
    status: {
      ACTIVE: '이미 진행 중인 듀얼입니다.',
      SETTLED: '이미 정산된 듀얼입니다.',
      CANCELLED: '도전자가 이 듀얼을 취소했습니다.',
      EXPIRED: '제때 수락한 사람이 없어 만료되었습니다.',
    } as Record<string, string>,
    winner: '승자',
    noWinner: '무승부 — 오간 것 없음',
    stakeLabel: '스테이크',
    windowLabel: '기간',
    windowValue: '24시간',
    learn: 'VOLTARA란?',
  },

  SQUAD: {
    eyebrow: '공유 그리드',
    title: '스쿼드',
    subtitle:
      '최대 다섯 명이 남는 냉각과 전력을 함께 씁니다. 내 여유가 팀원을 안정시키고, 팀원의 여유가 나를 지킵니다.',
    back: '대시보드',
    offline: '그리드에 연결할 수 없습니다. 잠시 후 다시 시도하세요.',
    createTitle: '스쿼드 만들기',
    createBody: '이름을 정하고, 최대 네 명에게 코드를 공유하세요.',
    namePlaceholder: '스쿼드 이름',
    create: '스쿼드 생성',
    joinTitle: '스쿼드 참가',
    joinBody: '스쿼드 소유자가 준 코드를 붙여넣으세요.',
    codePlaceholder: '스쿼드 코드',
    join: '참가',
    working: '처리 중…',
    code: '초대 코드',
    copy: '코드 복사',
    copied: '복사됨',
    share: '공유',
    shareText: (name: string) =>
      `VOLTARA에서 제 스쿼드 "${name}"에 합류하세요 — 냉각과 전력을 함께 써서 모든 리그를 100%로 유지합니다. 코드:`,
    leave: '스쿼드 탈퇴',
    leaveConfirm: '스쿼드를 나갈까요? 공유받던 냉각과 전력이 즉시 사라집니다.',
    owner: '소유자',
    members: '멤버',
    poolEyebrow: '공유 여유분',
    poolTitle: '공유 풀',
    poolBody: '모든 멤버의 남는 냉각과 전력을 모아, 한도를 넘긴 사람에게 빌려줍니다.',
    cooling: '냉각',
    power: '전력',
    lent: '대여 중',
    spare: '여유',
    unit: { cooling: 'TU', power: 'W' },
    earned7d: '스쿼드 7일 채굴량',
    memberRate: 'VOLTS / h',
    memberStability: '안정도',
    receiving: '수신',
    giving: '여유',
    boardTitle: '스쿼드 순위',
    boardBody: '최근 7일간 전체 멤버가 채굴한 VOLTS.',
    rank: '#',
    squadCol: '스쿼드',
    membersCol: '멤버',
    earnedCol: '7일 VOLTS',
    yours: '내 스쿼드',
    boardEmpty: '아직 순위에 오른 스쿼드가 없습니다.',
    full: (n: number, max: number) => `멤버 ${n} / ${max}`,
  },

  LEADERBOARD_LINKS: {
    duelsTitle: '리그 듀얼',
    duelsBody: '24시간 경쟁, 10% 스테이크. 채굴자에게 도전하세요.',
    squadTitle: '스쿼드',
    squadBody: '네 명과 냉각·전력을 함께 쓰세요.',
    open: '열기',
  },

  SEASON: {
    eyebrow: '이번 시즌',
    title: '주간 시즌',
    body: '월요일 00:00 UTC에 시작해 다음 월요일에 마감됩니다. 상위 10명이 VOLTS를 받습니다.',
    pool: '상금 풀',
    closesIn: '마감까지',
    closed: '마감됨',
    place: '순위',
    earned: '이번 주 채굴량',
    prize: '상금',
    projected: '예상',
    you: '나',
    yourPlace: '내 순위',
    unranked: '아직 순위 없음',
    unrankedHint: '이번 주에 VOLTS를 채굴하면 순위표에 올라갑니다.',
    outOf: (n: number) => `채굴자 ${n}명 중`,
    prizeIfHolds: '지금 순위를 지키면',
    noPrizeYet: '10위 안에 들면 상금을 받습니다',
    empty: '이번 시즌은 아직 아무도 채굴하지 않았습니다.',
    lastSeason: '지난 시즌',
    lastSeasonBody: (key: string) => `${key} 최종 결과 — 지급 완료.`,
    youWon: (volts: number) => `${volts} VOLTS 획득`,
    volts: 'VOLTS',
    watch: '리그 관전',
  },

  WATCH: {
    eyebrow: '관전 중',
    title: '리그 관전',
    subtitle: '그리드에서 실시간으로. 10초마다 갱신됩니다.',
    offline: '해당 리그에 연결할 수 없습니다.',
    notFound: '이 링크에 연결된 리그가 없습니다. 이미 사라졌을 수 있습니다.',
    loading: '연결 중…',
    stability: '그리드 안정도',
    rate: '산출량',
    perHour: 'VOLTS / h',
    parts: '가동 중인 부품',
    streak: '연속 기록',
    days: '일',
    joined: '채굴 시작',
    thermal: '발열 대비 냉각',
    power: '소비 대비 공급',
    overclocking: '오버클럭 중',
    hot: '과열 가동',
    burned: '소손',
    empty: '빈 슬롯',
    eventLive: '그리드 이벤트',
    challenge: '이 리그에 도전',
    signUpToChallenge: '가입하고 도전하기',
    backToBoard: '리더보드',
    watchCta: '관전',
    ownRig: '내 리그입니다',
    goToMine: '내 리그 열기',
  },

  APPRENTICE: {
    eyebrow: '멘토십',
    title: '견습생',
    subtitle:
      '신규 채굴자를 맡아 보세요. 남는 부품을 건네주고, 그가 캐낸 것의 일부를 받습니다. 그 몫은 새로 발행되며 그에게서 빼앗지 않습니다.',
    back: '대시보드',
    offline: '그리드에 연결할 수 없습니다. 잠시 후 다시 시도하세요.',
    heroTitle: '그리드를 지키는 법을 가르치세요',
    heroBody:
      '멘토는 견습생이 첫 30일 동안 캐낸 것의 5%를 받습니다. 이 몫은 새로 발행되므로 멘토를 두는 데 드는 비용은 없습니다.',
    pointTeachTitle: '쓰지 않는 부품을 건네세요',
    pointTeachBody: '보관함에 놓인 부품은 아무것도 벌지 않습니다. 견습생에게 주면 바로 그의 리그에 장착됩니다.',
    pointEarnTitle: '30일간 5%',
    pointEarnBody: '그가 수확할 때마다 그의 몫과 별개로 지급됩니다. 기간이 끝나므로 멘토십은 한 번의 도움이지 영구 수입이 아닙니다.',
    pointCapTitle: '동시에 세 명까지',
    pointCapBody: '멘토는 동시에 세 명까지 맡을 수 있고, 한 명을 더 받으려면 안정도 100%를 유지해야 합니다.',
    offerTitle: '견습생 받기',
    offerHint: '상대의 초대 코드를 붙여넣으세요. 상대가 수락해야 시작됩니다.',
    offerPlaceholder: '초대 코드',
    offerCta: '제안 보내기',
    offerSent: '제안을 보냈습니다. 수락을 기다리는 중입니다.',
    cannotMentor: '아직 견습생을 받을 수 없습니다',
    blockTooNew: (n: number) => `멘토링은 가입 후 일주일부터 가능합니다. ${n}일 남았습니다.`,
    blockUnstable: '내 리그가 먼저 안정도 100%를 유지해야 합니다.',
    blockCapacity: '이미 맡을 수 있는 만큼의 견습생이 있습니다.',
    blockIsApprentice: '멘토를 두고 있는 동안에는 멘토가 될 수 없습니다.',
    invitesTitle: '멘토 제안을 받았습니다',
    invitesBody: '그는 30일 동안 당신이 캐낸 것의 5%를 받습니다. 당신이 잃는 것은 없습니다.',
    accept: '수락',
    decline: '거절',
    pendingTitle: '수락 대기 중',
    activeTitle: '내 견습생',
    activeEmpty: '아직 견습생이 없습니다.',
    myMentorTitle: '내 멘토',
    noMentor: '멘토가 없습니다.',
    end: '종료',
    endConfirm: '이 멘토십을 끝낼까요? 같은 채굴자와 다시 시작할 수 없습니다.',
    gift: '부품 선물',
    giftTitle: '부품 선물',
    giftHint: '장착되지 않은 부품만 건넬 수 있습니다.',
    giftEmpty: '보관함에 남는 부품이 없습니다.',
    giftCta: '건네주기',
    gifted: '전달했습니다. 바로 그의 리그에 장착되었습니다.',
    earned: '멘토로서 얻은 수익',
    cutEnds: '몫 종료',
    cutEnded: '몫이 끝났습니다',
    stability: '안정도',
    rate: '산출량',
    watch: '리그 관전',
    joined: '가입일',
    roleMentor: '내가 멘토입니다',
    roleApprentice: '그가 내 멘토입니다',
  },
};

const BY_LOCALE: Record<string, Copy> = { en, zh, ko };

/** Copy for the active locale; falls back to English. */
export function useSocial(): Copy {
  const locale = useLocale();
  return BY_LOCALE[locale] ?? en;
}

/** English copy, for anything that cannot call a hook. */
export const DUELS = en.DUELS;
export const DUEL_LANDING = en.DUEL_LANDING;
export const SQUAD = en.SQUAD;
export const LEADERBOARD_LINKS = en.LEADERBOARD_LINKS;
