import { useI18n } from '../../i18n';

/**
 * Copy for the two competitive screens: rig duels and squads.
 *
 * Kept out of the shared catalogues so the three locale files do not have to
 * move in step with a feature that is still settling. Typing `zh` and `ko` as
 * `Copy` makes a missing translation a compile error rather than a blank
 * label on a phone.
 *
 * Brand terms stay untranslated: VOLTARA, $VLTR, VOLTS, TU, W.
 */
const en = {
  // ── Duels ──
  duelsTitle: 'Rig Duels',
  duelsSubtitle: 'Race another rig for 24 hours.',
  duelsPitchTitle: 'Put your build on the line',
  duelsPitchBody:
    'Send a link. The first miner to accept races you for 24 hours, and the rig that mines more VOLTS wins.',
  duelsPoint1Title: '24-hour window',
  duelsPoint1Body: 'Only what each rig mines inside the window counts.',
  duelsPoint2Title: '10% stake',
  duelsPoint2Body: 'The loser hands over a tenth of what they mined in the race.',
  duelsPoint3Title: 'Your build, not your balance',
  duelsPoint3Body: 'Cooling and power decide this, so a cheap rig can beat an expensive one.',
  duelCreate: 'Create duel',
  duelCreating: 'Creating…',

  duelOpenTitle: 'Waiting for a challenger',
  duelOpenBody: 'Share this link. The duel starts the moment somebody accepts.',
  duelOpenExpires: 'Expires in',
  duelLink: 'Duel link',
  duelCopy: 'Copy link',
  duelShare: 'Share',
  duelCancel: 'Cancel duel',
  duelCancelTitle: 'Cancel this duel?',
  duelCancelBody: 'The link stops working and nobody can accept it.',
  duelCancelConfirm: 'Cancel duel',
  duelKeep: 'Keep it',
  duelShareMessage: 'My VOLTARA rig is up for a 24h duel. Think yours is faster? {link}',
  duelShareTitle: 'VOLTARA rig duel',

  duelActiveTitle: 'Duel running',
  duelEndsIn: 'Ends in',
  duelYou: 'You',
  duelOpponent: 'Opponent',
  duelLeading: 'Leading',
  duelTrailing: 'Trailing',
  duelTied: 'Level',
  duelStake: 'Stake',
  duelRate: 'Rate',
  duelStability: 'Stability',
  duelScore: 'Mined in window',

  duelHistoryTitle: 'Past duels',
  duelHistoryEmpty: 'No duels yet.',
  duelWon: 'Won',
  duelLost: 'Lost',
  duelDraw: 'Draw',
  duelExpired: 'Expired',
  duelCancelled: 'Cancelled',
  duelTransferred: 'transferred',
  duelNothingMoved: 'nothing moved',

  // ── Squads ──
  squadTitle: 'Squad',
  squadSubtitle: 'Share cooling and power with four friends.',
  squadPitchBody:
    'Every member’s unused cooling and power go into a pool. Anyone over budget draws from it, so one big cooler steadies the whole squad.',
  squadCreateTitle: 'Create a squad',
  squadCreateHint: 'You become the owner and get a code to share.',
  squadNameLabel: 'Squad name',
  squadNamePlaceholder: '3 to 24 characters',
  squadCreate: 'Create squad',
  squadJoinTitle: 'Join a squad',
  squadJoinHint: 'Paste the code a squad mate sent you.',
  squadCodeLabel: 'Squad code',
  squadCodePlaceholder: 'Paste code',
  squadJoin: 'Join squad',

  squadMembers: 'Members',
  squadEarned7d: 'Mined in 7 days',
  squadCode: 'Squad code',
  squadShareMessage: 'Join my VOLTARA squad and pool cooling and power. Code: {code}',
  squadShareTitle: 'VOLTARA squad',
  squadPoolTitle: 'Shared pool',
  squadPoolHint: 'Spare capacity is lent to whoever is over budget.',
  squadCooling: 'Cooling',
  squadPower: 'Power',
  squadLent: 'lent',
  squadSpare: 'spare',
  squadPoolIdle: 'Nobody needs help right now.',
  squadOwner: 'Owner',
  squadReceiving: 'Receiving',
  squadSparePrefix: 'Spare',
  squadLeave: 'Leave squad',
  squadLeaveTitle: 'Leave this squad?',
  squadLeaveBody: 'You stop lending and receiving capacity right away.',
  squadLeaveOwnerBody:
    'You own this squad, so ownership passes to the member who joined first.',
  squadLeaveConfirm: 'Leave',
  squadStay: 'Stay',

  squadRanksTitle: 'Squad rankings',
  squadRanksEmpty: 'No squads have mined yet this week.',
  squadRankCol: 'Rank',
  squadYours: 'Yours',

  // ── Shared ──
  volts: 'VOLTS',
  perHour: '/h',
  linkTo: 'Duels and squads',
  duelsLinkHint: 'Race another rig for 24 hours',
  squadLinkHint: 'Pool cooling and power with friends',

  // ── Spectating ──
  watchTitle: 'Watching a rig',
  watchSubtitle: 'Live from the grid, every ten seconds.',
  watchOffline: 'Could not reach that rig.',
  watchNotFound: 'No rig behind that link.',
  watchStability: 'Grid stability',
  watchRate: 'Output',
  watchParts: 'Parts running',
  watchThermal: 'Heat vs cooling',
  watchPower: 'Draw vs supply',
  watchOverclocking: 'Overclocking',
  watchHot: 'Running hot',
  watchBurned: 'Burned',
  watchEmpty: 'Empty socket',
  watchEvent: 'Grid event',
  watchStreak: 'Streak',
  watchDays: 'days',
  watchChallenge: 'Challenge this rig',
  watchCta: 'Watch rig',

  // ── Apprenticeship ──
  apprenticeTitle: 'Apprentices',
  apprenticeSubtitle: 'Adopt a newcomer. Your share is minted on top, never taken from them.',
  apprenticeOffline: 'Could not reach the grid. Try again in a moment.',
  apprenticeHeroTitle: 'Teach someone to hold the grid',
  apprenticeHeroBody:
    'A mentor keeps 5% of what their apprentice mines for the first 30 days, newly minted — so being mentored costs a newcomer nothing.',
  apprenticeOfferTitle: 'Take on an apprentice',
  apprenticeOfferHint: 'Paste their invite code. They have to accept first.',
  apprenticeOfferPlaceholder: 'Invite code',
  apprenticeOfferCta: 'Send offer',
  apprenticeOfferSent: 'Offer sent.',
  apprenticeCannot: 'You cannot take on an apprentice yet',
  apprenticeBlockTooNew: 'Mentoring opens after your first week.',
  apprenticeBlockUnstable: 'Your rig has to be holding 100% stability first.',
  apprenticeBlockCapacity: 'You already have as many apprentices as you can hold.',
  apprenticeBlockIsApprentice: 'You cannot mentor while you are being mentored.',
  apprenticeInviteTitle: 'You have been offered a mentor',
  apprenticeInviteBody: 'They keep 5% of what you mine for 30 days. It costs you nothing.',
  apprenticeAccept: 'Accept',
  apprenticeDecline: 'Decline',
  apprenticePending: 'Waiting to be accepted',
  apprenticeActive: 'Your apprentices',
  apprenticeEmpty: 'No apprentices yet.',
  apprenticeMyMentor: 'Your mentor',
  apprenticeNoMentor: 'You have no mentor.',
  apprenticeEnd: 'End',
  apprenticeEndConfirm: 'End this apprenticeship? It cannot be restarted.',
  apprenticeGift: 'Gift a part',
  apprenticeGiftHint: 'Only parts that are not installed can be handed over.',
  apprenticeGiftEmpty: 'Nothing spare in your inventory.',
  apprenticeGiftCta: 'Hand it over',
  apprenticeGifted: 'Sent straight into their rig.',
  apprenticeEarned: 'Earned as a mentor',
  apprenticeCutEnds: 'Share ends',
  apprenticeCutEnded: 'Share has ended',
  apprenticeRoleMentor: 'You mentor them',
  apprenticeRoleApprentice: 'They mentor you',
  apprenticeLink: 'Apprentices',
  apprenticeLinkHint: 'Mentor a newcomer, earn a minted share',
  apprenticeKeep: 'Keep it',

  // ── Weekly season ──
  seasonEyebrow: 'This season',
  seasonTitle: 'Weekly season',
  seasonBody: 'Opens Monday 00:00 UTC and settles the following Monday. The top ten miners are paid in VOLTS.',
  seasonPool: 'Prize pool',
  seasonClosesIn: 'Closes in',
  seasonPlace: 'Place',
  seasonEarned: 'Mined this week',
  seasonPrize: 'Prize',
  seasonProjected: 'Projected',
  seasonYou: 'You',
  seasonYourPlace: 'Your place',
  seasonUnranked: 'Not ranked yet',
  seasonUnrankedHint: 'Mine any VOLTS this week and you join the table.',
  seasonOutOf: 'miners',
  seasonPrizeIfHolds: 'If you hold this place',
  seasonNoPrizeYet: 'Reach the top ten to win a prize',
  seasonEmpty: 'Nobody has mined this season yet.',
  seasonLast: 'Last season',
  seasonLastBody: 'final standings — paid out.',
  seasonYouWon: 'You won',
  seasonVolts: 'VOLTS',
} as const;

/**
 * Every key of `en`, each holding any string. The mapping keeps a missing or
 * misspelled key a compile error while letting a translation differ from the
 * English literal that `as const` would otherwise pin it to.
 */
type Copy = { [K in keyof typeof en]: string };

const zh: Copy = {
  duelsTitle: '矿机对决',
  duelsSubtitle: '与另一台矿机比拼 24 小时。',
  duelsPitchTitle: '用你的配置一决高下',
  duelsPitchBody:
    '发出链接。第一位接受的矿工将与你比拼 24 小时，挖到更多 VOLTS 的矿机获胜。',
  duelsPoint1Title: '24 小时窗口',
  duelsPoint1Body: '只统计窗口期内各自挖到的数量。',
  duelsPoint2Title: '10% 赌注',
  duelsPoint2Body: '落败方交出自己在比拼期间所挖数量的十分之一。',
  duelsPoint3Title: '比的是配置，不是余额',
  duelsPoint3Body: '胜负取决于散热与供电，便宜的矿机也能击败昂贵的。',
  duelCreate: '发起对决',
  duelCreating: '创建中…',

  duelOpenTitle: '等待挑战者',
  duelOpenBody: '分享此链接。有人接受后对决立即开始。',
  duelOpenExpires: '过期于',
  duelLink: '对决链接',
  duelCopy: '复制链接',
  duelShare: '分享',
  duelCancel: '取消对决',
  duelCancelTitle: '取消这场对决？',
  duelCancelBody: '链接将失效，任何人都无法再接受。',
  duelCancelConfirm: '取消对决',
  duelKeep: '保留',
  duelShareMessage: '我的 VOLTARA 矿机开启了 24 小时对决。你的更快吗？{link}',
  duelShareTitle: 'VOLTARA 矿机对决',

  duelActiveTitle: '对决进行中',
  duelEndsIn: '结束于',
  duelYou: '你',
  duelOpponent: '对手',
  duelLeading: '领先',
  duelTrailing: '落后',
  duelTied: '打平',
  duelStake: '赌注',
  duelRate: '速率',
  duelStability: '稳定度',
  duelScore: '窗口期产出',

  duelHistoryTitle: '历史对决',
  duelHistoryEmpty: '还没有对决记录。',
  duelWon: '获胜',
  duelLost: '落败',
  duelDraw: '平局',
  duelExpired: '已过期',
  duelCancelled: '已取消',
  duelTransferred: '已转移',
  duelNothingMoved: '没有转移',

  squadTitle: '小队',
  squadSubtitle: '与四位好友共享散热与供电。',
  squadPitchBody:
    '每位成员未用完的散热与供电进入共享池。任何超出预算的成员都可以从中取用，一台大散热器就能稳住整个小队。',
  squadCreateTitle: '创建小队',
  squadCreateHint: '你将成为队长，并获得可分享的代码。',
  squadNameLabel: '小队名称',
  squadNamePlaceholder: '3 到 24 个字符',
  squadCreate: '创建小队',
  squadJoinTitle: '加入小队',
  squadJoinHint: '粘贴队友发给你的代码。',
  squadCodeLabel: '小队代码',
  squadCodePlaceholder: '粘贴代码',
  squadJoin: '加入小队',

  squadMembers: '成员',
  squadEarned7d: '7 天产出',
  squadCode: '小队代码',
  squadShareMessage: '加入我的 VOLTARA 小队，共享散热与供电。代码：{code}',
  squadShareTitle: 'VOLTARA 小队',
  squadPoolTitle: '共享池',
  squadPoolHint: '空余容量会借给超出预算的成员。',
  squadCooling: '散热',
  squadPower: '供电',
  squadLent: '已借出',
  squadSpare: '空余',
  squadPoolIdle: '目前没有人需要支援。',
  squadOwner: '队长',
  squadReceiving: '获得',
  squadSparePrefix: '空余',
  squadLeave: '退出小队',
  squadLeaveTitle: '退出这个小队？',
  squadLeaveBody: '你将立即停止借出与获得容量。',
  squadLeaveOwnerBody: '你是队长，队长身份将转给最早加入的成员。',
  squadLeaveConfirm: '退出',
  squadStay: '留下',

  squadRanksTitle: '小队排行',
  squadRanksEmpty: '本周还没有小队产出。',
  squadRankCol: '排名',
  squadYours: '我的',

  volts: 'VOLTS',
  perHour: '/小时',
  linkTo: '对决与小队',
  duelsLinkHint: '与另一台矿机比拼 24 小时',
  squadLinkHint: '与好友共享散热与供电',

  // ── 观战 ──
  watchTitle: '正在观看一台矿机',
  watchSubtitle: '来自电网的实时画面，每十秒更新。',
  watchOffline: '无法连接到这台矿机。',
  watchNotFound: '该链接背后没有矿机。',
  watchStability: '电网稳定度',
  watchRate: '产出',
  watchParts: '运行中的部件',
  watchThermal: '热量与散热',
  watchPower: '功耗与供电',
  watchOverclocking: '超频中',
  watchHot: '过热运行',
  watchBurned: '已烧毁',
  watchEmpty: '空插槽',
  watchEvent: '电网事件',
  watchStreak: '连续天数',
  watchDays: '天',
  watchChallenge: '向这台矿机挑战',
  watchCta: '观看矿机',

  // ── 师徒 ──
  apprenticeTitle: '学徒',
  apprenticeSubtitle: '收一位新人为徒。你的份额是额外增发的，绝不从他那里扣除。',
  apprenticeOffline: '无法连接电网，请稍后再试。',
  apprenticeHeroTitle: '教会别人稳住电网',
  apprenticeHeroBody:
    '师父可获得徒弟前 30 天产出的 5%，且为额外增发——所以拜师对新人完全免费。',
  apprenticeOfferTitle: '收一位学徒',
  apprenticeOfferHint: '粘贴他的邀请码，需要对方先接受。',
  apprenticeOfferPlaceholder: '邀请码',
  apprenticeOfferCta: '发送邀请',
  apprenticeOfferSent: '邀请已发送。',
  apprenticeCannot: '你目前还不能收学徒',
  apprenticeBlockTooNew: '满一周后才能收徒。',
  apprenticeBlockUnstable: '你的矿机需要先保持 100% 稳定度。',
  apprenticeBlockCapacity: '你带的学徒已达上限。',
  apprenticeBlockIsApprentice: '你自己还在拜师期间，不能收徒。',
  apprenticeInviteTitle: '有人想收你为徒',
  apprenticeInviteBody: '他将在 30 天内获得你产出的 5%。这对你没有任何花费。',
  apprenticeAccept: '接受',
  apprenticeDecline: '拒绝',
  apprenticePending: '等待对方接受',
  apprenticeActive: '你的学徒',
  apprenticeEmpty: '还没有学徒。',
  apprenticeMyMentor: '你的师父',
  apprenticeNoMentor: '你还没有师父。',
  apprenticeEnd: '结束',
  apprenticeEndConfirm: '结束这段师徒关系？无法重新建立。',
  apprenticeGift: '赠送部件',
  apprenticeGiftHint: '只有未装机的部件可以送出。',
  apprenticeGiftEmpty: '仓库里没有闲置部件。',
  apprenticeGiftCta: '送出',
  apprenticeGifted: '已直接装进他的矿机。',
  apprenticeEarned: '作为师父的收益',
  apprenticeCutEnds: '份额结束于',
  apprenticeCutEnded: '份额已结束',
  apprenticeRoleMentor: '你是他的师父',
  apprenticeRoleApprentice: '他是你的师父',
  apprenticeLink: '学徒',
  apprenticeLinkHint: '收徒并获得额外增发的份额',
  apprenticeKeep: '保持',

  // ── Weekly season ──
  seasonEyebrow: '本赛季',
  seasonTitle: '每周赛季',
  seasonBody: '每周一 00:00 UTC 开始，下周一结算。前十名矿工可获得 VOLTS。',
  seasonPool: '奖池',
  seasonClosesIn: '距结算',
  seasonPlace: '名次',
  seasonEarned: '本周产出',
  seasonPrize: '奖励',
  seasonProjected: '预计',
  seasonYou: '你',
  seasonYourPlace: '你的名次',
  seasonUnranked: '尚未上榜',
  seasonUnrankedHint: '本周挖到 VOLTS 即可进入排行。',
  seasonOutOf: '名矿工中',
  seasonPrizeIfHolds: '若保持当前名次',
  seasonNoPrizeYet: '进入前十即可获得奖励',
  seasonEmpty: '本赛季还没有人开始挖矿。',
  seasonLast: '上个赛季',
  seasonLastBody: '最终结果 — 奖励已发放。',
  seasonYouWon: '你赢得了',
  seasonVolts: 'VOLTS',
};

const ko: Copy = {
  duelsTitle: '리그 대결',
  duelsSubtitle: '다른 리그와 24시간 동안 경쟁합니다.',
  duelsPitchTitle: '내 빌드로 승부하기',
  duelsPitchBody:
    '링크를 보내세요. 먼저 수락한 채굴자와 24시간 동안 경쟁하고, VOLTS를 더 많이 캔 리그가 이깁니다.',
  duelsPoint1Title: '24시간 구간',
  duelsPoint1Body: '구간 안에서 각 리그가 캔 양만 계산합니다.',
  duelsPoint2Title: '10% 배팅',
  duelsPoint2Body: '진 쪽이 대결 중 캔 양의 10분의 1을 넘겨줍니다.',
  duelsPoint3Title: '잔액이 아니라 빌드 싸움',
  duelsPoint3Body: '냉각과 전력이 승부를 가르므로 저렴한 리그도 이길 수 있습니다.',
  duelCreate: '대결 만들기',
  duelCreating: '만드는 중…',

  duelOpenTitle: '도전자를 기다리는 중',
  duelOpenBody: '이 링크를 공유하세요. 누군가 수락하면 바로 시작됩니다.',
  duelOpenExpires: '만료까지',
  duelLink: '대결 링크',
  duelCopy: '링크 복사',
  duelShare: '공유',
  duelCancel: '대결 취소',
  duelCancelTitle: '이 대결을 취소할까요?',
  duelCancelBody: '링크가 작동하지 않게 되고 아무도 수락할 수 없습니다.',
  duelCancelConfirm: '대결 취소',
  duelKeep: '유지',
  duelShareMessage: '제 VOLTARA 리그가 24시간 대결을 기다립니다. 더 빠르다고 생각하세요? {link}',
  duelShareTitle: 'VOLTARA 리그 대결',

  duelActiveTitle: '대결 진행 중',
  duelEndsIn: '종료까지',
  duelYou: '나',
  duelOpponent: '상대',
  duelLeading: '앞서는 중',
  duelTrailing: '뒤처지는 중',
  duelTied: '동점',
  duelStake: '배팅',
  duelRate: '채굴 속도',
  duelStability: '안정도',
  duelScore: '구간 채굴량',

  duelHistoryTitle: '지난 대결',
  duelHistoryEmpty: '아직 대결 기록이 없습니다.',
  duelWon: '승리',
  duelLost: '패배',
  duelDraw: '무승부',
  duelExpired: '만료됨',
  duelCancelled: '취소됨',
  duelTransferred: '이동함',
  duelNothingMoved: '이동 없음',

  squadTitle: '스쿼드',
  squadSubtitle: '친구 넷과 냉각과 전력을 함께 씁니다.',
  squadPitchBody:
    '멤버가 쓰지 않는 냉각과 전력이 공용 풀에 모입니다. 예산을 넘긴 멤버가 여기서 가져가므로 큰 쿨러 하나가 스쿼드 전체를 안정시킵니다.',
  squadCreateTitle: '스쿼드 만들기',
  squadCreateHint: '당신이 소유자가 되고 공유할 코드를 받습니다.',
  squadNameLabel: '스쿼드 이름',
  squadNamePlaceholder: '3~24자',
  squadCreate: '스쿼드 만들기',
  squadJoinTitle: '스쿼드 참가',
  squadJoinHint: '팀원이 보낸 코드를 붙여넣으세요.',
  squadCodeLabel: '스쿼드 코드',
  squadCodePlaceholder: '코드 붙여넣기',
  squadJoin: '스쿼드 참가',

  squadMembers: '멤버',
  squadEarned7d: '7일 채굴량',
  squadCode: '스쿼드 코드',
  squadShareMessage: '제 VOLTARA 스쿼드에 참가해 냉각과 전력을 함께 쓰세요. 코드: {code}',
  squadShareTitle: 'VOLTARA 스쿼드',
  squadPoolTitle: '공용 풀',
  squadPoolHint: '남는 용량은 예산을 넘긴 멤버에게 빌려줍니다.',
  squadCooling: '냉각',
  squadPower: '전력',
  squadLent: '빌려줌',
  squadSpare: '여유',
  squadPoolIdle: '지금은 도움이 필요한 멤버가 없습니다.',
  squadOwner: '소유자',
  squadReceiving: '받는 중',
  squadSparePrefix: '여유',
  squadLeave: '스쿼드 나가기',
  squadLeaveTitle: '이 스쿼드를 나갈까요?',
  squadLeaveBody: '즉시 용량을 빌려주거나 받지 않게 됩니다.',
  squadLeaveOwnerBody: '당신이 소유자이므로 가장 먼저 참가한 멤버에게 소유권이 넘어갑니다.',
  squadLeaveConfirm: '나가기',
  squadStay: '남기',

  squadRanksTitle: '스쿼드 순위',
  squadRanksEmpty: '이번 주에 채굴한 스쿼드가 아직 없습니다.',
  squadRankCol: '순위',
  squadYours: '내 스쿼드',

  volts: 'VOLTS',
  perHour: '/시간',
  linkTo: '대결과 스쿼드',
  duelsLinkHint: '다른 리그와 24시간 경쟁',
  squadLinkHint: '친구와 냉각·전력 공유',

  // ── 관전 ──
  watchTitle: '리그 관전',
  watchSubtitle: '그리드에서 실시간으로, 10초마다 갱신.',
  watchOffline: '해당 리그에 연결할 수 없습니다.',
  watchNotFound: '이 링크에 연결된 리그가 없습니다.',
  watchStability: '그리드 안정도',
  watchRate: '산출량',
  watchParts: '가동 중인 부품',
  watchThermal: '발열 대비 냉각',
  watchPower: '소비 대비 공급',
  watchOverclocking: '오버클럭 중',
  watchHot: '과열 가동',
  watchBurned: '소손',
  watchEmpty: '빈 슬롯',
  watchEvent: '그리드 이벤트',
  watchStreak: '연속 기록',
  watchDays: '일',
  watchChallenge: '이 리그에 도전',
  watchCta: '리그 관전',

  // ── 멘토십 ──
  apprenticeTitle: '견습생',
  apprenticeSubtitle: '신규 채굴자를 맡아 보세요. 내 몫은 새로 발행되며 그에게서 빼앗지 않습니다.',
  apprenticeOffline: '그리드에 연결할 수 없습니다. 잠시 후 다시 시도하세요.',
  apprenticeHeroTitle: '그리드를 지키는 법을 가르치세요',
  apprenticeHeroBody:
    '멘토는 견습생이 첫 30일간 캐낸 것의 5%를 새로 발행받습니다. 그래서 멘토를 두는 데 드는 비용은 없습니다.',
  apprenticeOfferTitle: '견습생 받기',
  apprenticeOfferHint: '상대의 초대 코드를 붙여넣으세요. 상대가 먼저 수락해야 합니다.',
  apprenticeOfferPlaceholder: '초대 코드',
  apprenticeOfferCta: '제안 보내기',
  apprenticeOfferSent: '제안을 보냈습니다.',
  apprenticeCannot: '아직 견습생을 받을 수 없습니다',
  apprenticeBlockTooNew: '멘토링은 가입 후 일주일부터 가능합니다.',
  apprenticeBlockUnstable: '내 리그가 먼저 안정도 100%를 유지해야 합니다.',
  apprenticeBlockCapacity: '이미 맡을 수 있는 만큼의 견습생이 있습니다.',
  apprenticeBlockIsApprentice: '멘토를 두고 있는 동안에는 멘토가 될 수 없습니다.',
  apprenticeInviteTitle: '멘토 제안을 받았습니다',
  apprenticeInviteBody: '그는 30일 동안 당신이 캐낸 것의 5%를 받습니다. 당신이 잃는 것은 없습니다.',
  apprenticeAccept: '수락',
  apprenticeDecline: '거절',
  apprenticePending: '수락 대기 중',
  apprenticeActive: '내 견습생',
  apprenticeEmpty: '아직 견습생이 없습니다.',
  apprenticeMyMentor: '내 멘토',
  apprenticeNoMentor: '멘토가 없습니다.',
  apprenticeEnd: '종료',
  apprenticeEndConfirm: '이 멘토십을 끝낼까요? 다시 시작할 수 없습니다.',
  apprenticeGift: '부품 선물',
  apprenticeGiftHint: '장착되지 않은 부품만 건넬 수 있습니다.',
  apprenticeGiftEmpty: '보관함에 남는 부품이 없습니다.',
  apprenticeGiftCta: '건네주기',
  apprenticeGifted: '바로 그의 리그에 장착되었습니다.',
  apprenticeEarned: '멘토로서 얻은 수익',
  apprenticeCutEnds: '몫 종료',
  apprenticeCutEnded: '몫이 끝났습니다',
  apprenticeRoleMentor: '내가 멘토입니다',
  apprenticeRoleApprentice: '그가 내 멘토입니다',
  apprenticeLink: '견습생',
  apprenticeLinkHint: '신규 채굴자를 맡고 발행된 몫을 받기',
  apprenticeKeep: '유지',

  // ── Weekly season ──
  seasonEyebrow: '이번 시즌',
  seasonTitle: '주간 시즌',
  seasonBody: '월요일 00:00 UTC에 시작해 다음 월요일에 마감됩니다. 상위 10명이 VOLTS를 받습니다.',
  seasonPool: '상금 풀',
  seasonClosesIn: '마감까지',
  seasonPlace: '순위',
  seasonEarned: '이번 주 채굴량',
  seasonPrize: '상금',
  seasonProjected: '예상',
  seasonYou: '나',
  seasonYourPlace: '내 순위',
  seasonUnranked: '아직 순위 없음',
  seasonUnrankedHint: '이번 주에 VOLTS를 채굴하면 순위표에 올라갑니다.',
  seasonOutOf: '명 중',
  seasonPrizeIfHolds: '지금 순위를 지키면',
  seasonNoPrizeYet: '10위 안에 들면 상금을 받습니다',
  seasonEmpty: '이번 시즌은 아직 아무도 채굴하지 않았습니다.',
  seasonLast: '지난 시즌',
  seasonLastBody: '최종 결과 — 지급 완료.',
  seasonYouWon: '획득',
  seasonVolts: 'VOLTS',
};

const BY_LOCALE: Record<string, Copy> = { en, zh, ko };

/** Duel and squad copy for the active locale; falls back to English. */
export function useSocial(): Copy {
  const { locale } = useI18n();
  return BY_LOCALE[locale] ?? en;
}

/** English copy, for call sites outside a component. */
export const SOCIAL = en;
