import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma.service';

/**
 * Visit counting.
 *
 * The whole feature is one table and two methods, and most of the thinking is
 * about what the number is allowed to claim. A visit here is a browsing
 * session: one row per `sessionStorage` id, written once by a beacon the
 * browser fires after the page loads.
 *
 * What that gets right: it does not count bots, because almost none of them
 * run the script, and it does not double count a visitor who clicks through
 * four pages, because the id survives the navigation.
 *
 * What it cannot do, and what the admin panel therefore has to say out loud:
 * it cannot tell you people. Two tabs are two visits and so is coming back
 * tomorrow. It is also a public unauthenticated counter, so it can be
 * inflated by anyone willing to POST random ids in a loop -- fine for "is
 * Reddit worth more effort than Kakao", useless as a number to report to
 * anyone else as truth.
 */

/** Session ids are generated by us; anything else is not from our beacon. */
const ID_RE = /^[A-Za-z0-9_-]{16,40}$/;

const MAX_PATH = 160;
const MAX_REFERRER = 120;
const MAX_LOCALE = 8;

export interface VisitBeacon {
  id?: unknown;
  path?: unknown;
  locale?: unknown;
  referrer?: unknown;
}

/**
 * Keep the referring host, drop everything after it.
 *
 * `https://www.reddit.com/r/incremental_games/comments/abc/...` becomes
 * `reddit.com`, which answers the only question this is for -- which channel
 * is working -- without recording the thread someone came from. Our own host
 * returns null: an internal navigation is not a referral.
 */
export function referrerHost(raw: unknown, selfHosts: string[]): string | null {
  if (typeof raw !== 'string' || raw.length === 0) return null;
  let host: string;
  try {
    host = new URL(raw).hostname.toLowerCase();
  } catch {
    return null;
  }
  if (!host) return null;
  const bare = host.startsWith('www.') ? host.slice(4) : host;
  if (selfHosts.includes(bare)) return null;
  return bare.slice(0, MAX_REFERRER);
}

/**
 * Strip the locale prefix so `/en/faq`, `/zh/faq` and `/ko/faq` count as one
 * page. The locale is recorded separately, so nothing is lost.
 */
export function normalisePath(raw: unknown): string | null {
  if (typeof raw !== 'string' || !raw.startsWith('/')) return null;
  const withoutQuery = raw.split(/[?#]/)[0];
  const stripped = withoutQuery.replace(/^\/(en|zh|ko)(?=\/|$)/, '');
  return (stripped || '/').slice(0, MAX_PATH);
}

export interface VisitTotals {
  allTime: number;
  last30d: number;
  last7d: number;
  today: number;
  byReferrer: { referrer: string; visits: number }[];
  byLocale: { locale: string; visits: number }[];
  topPaths: { path: string; visits: number }[];
  /** Honest label for the admin panel, not decoration. */
  counts: string;
}

@Injectable()
export class VisitsService {
  private readonly logger = new Logger(VisitsService.name);

  constructor(private readonly prisma: PrismaService) {}

  private selfHosts(): string[] {
    const web = process.env.WEB_URL || 'https://voltaragrid.com';
    try {
      const h = new URL(web).hostname.toLowerCase();
      const bare = h.startsWith('www.') ? h.slice(4) : h;
      return [bare, 'localhost'];
    } catch {
      return ['voltaragrid.com', 'localhost'];
    }
  }

  /**
   * Record a session. Returns quietly on anything malformed.
   *
   * The primary key does the deduplication, so a retry or a double fire is
   * free rather than a second visit. A failure here must never surface to the
   * visitor: this is a counter, and a counter is not worth an error on
   * someone's first page load.
   */
  async record(beacon: VisitBeacon): Promise<void> {
    const id = typeof beacon.id === 'string' ? beacon.id : '';
    if (!ID_RE.test(id)) return;

    const locale =
      typeof beacon.locale === 'string' ? beacon.locale.slice(0, MAX_LOCALE) : null;

    try {
      await this.prisma.visitSession.create({
        data: {
          id,
          locale,
          path: normalisePath(beacon.path),
          referrer: referrerHost(beacon.referrer, this.selfHosts()),
        },
      });
    } catch (err: unknown) {
      // P2002 is the id already existing, which is the beacon working as
      // intended. Anything else is worth a line in the log but not a throw.
      const code = (err as { code?: string })?.code;
      if (code !== 'P2002') {
        this.logger.warn(`Visit not recorded: ${String(err)}`);
      }
    }
  }

  /** Everything the admin panel shows about visits. */
  async totals(now = new Date()): Promise<VisitTotals> {
    const startOfToday = new Date(now);
    startOfToday.setUTCHours(0, 0, 0, 0);
    const since = (days: number) =>
      new Date(now.getTime() - days * 24 * 60 * 60 * 1000);

    const [allTime, last30d, last7d, today, referrers, locales, paths] =
      await Promise.all([
        this.prisma.visitSession.count(),
        this.prisma.visitSession.count({ where: { startedAt: { gte: since(30) } } }),
        this.prisma.visitSession.count({ where: { startedAt: { gte: since(7) } } }),
        this.prisma.visitSession.count({ where: { startedAt: { gte: startOfToday } } }),
        this.prisma.visitSession.groupBy({
          by: ['referrer'],
          where: { startedAt: { gte: since(30) }, referrer: { not: null } },
          _count: { _all: true },
          orderBy: { _count: { referrer: 'desc' } },
          take: 8,
        }),
        this.prisma.visitSession.groupBy({
          by: ['locale'],
          where: { startedAt: { gte: since(30) }, locale: { not: null } },
          _count: { _all: true },
          orderBy: { _count: { locale: 'desc' } },
          take: 8,
        }),
        this.prisma.visitSession.groupBy({
          by: ['path'],
          where: { startedAt: { gte: since(30) }, path: { not: null } },
          _count: { _all: true },
          orderBy: { _count: { path: 'desc' } },
          take: 8,
        }),
      ]);

    return {
      allTime,
      last30d,
      last7d,
      today,
      byReferrer: referrers.map((r) => ({
        referrer: r.referrer as string,
        visits: r._count._all,
      })),
      byLocale: locales.map((r) => ({
        locale: r.locale as string,
        visits: r._count._all,
      })),
      topPaths: paths.map((r) => ({ path: r.path as string, visits: r._count._all })),
      counts:
        'Browsing sessions, not people. A new tab or a return tomorrow counts ' +
        'again. Bots are excluded because the beacon needs JavaScript. Direct ' +
        'visits have no referrer and are not in the referrer list.',
    };
  }
}
