'use client';

import { useLocale } from 'next-intl';

/**
 * UI copy for the player market and the weekly blueprint challenge.
 *
 * `en` is deliberately NOT `as const` — widening the values to `string` is
 * what lets `zh` and `ko` be typed as `Copy`, so TypeScript fails the build
 * on a key that was added to one locale and forgotten in another.
 */
const en = {
  market: {
    segmentShop: 'Parts shop',
    segmentMarket: 'Player market',
    title: 'Player market',
    subtitle:
      'Buy and sell owned parts with other miners, paid in VOLTS. The grid keeps 5% of every sale.',
    filterAll: 'All',
    sell: 'Sell a part',
    empty: 'No parts for sale right now. List one of yours, or check back after the next event.',
    emptyFiltered: 'Nothing of this kind is listed at the moment.',
    daysLeft: 'left',
    seller: 'Seller',
    buy: 'Buy',
    yours: 'Yours',
    confirmTitle: 'Confirm purchase',
    confirmBody: 'The part moves to your rig the moment the sale clears. Sales are final.',
    price: 'Price',
    balance: 'Your balance',
    after: 'After purchase',
    insufficient: 'Not enough VOLTS for this part.',
    confirm: 'Pay and install',
    cancel: 'Cancel',
    close: 'Close',
    boughtInstalled: (n: number) => `Bought. Installed in slot ${n}.`,
    boughtInventory: 'Bought. Your rig is full, so the part went to inventory.',
    sellTitle: 'Sell a part',
    sellBody:
      'Only uninstalled parts with more than three days left can be listed. Remove a part from your rig first if you want to sell it.',
    sellNone: 'Nothing in inventory to sell. Uninstall a part on the rig page first.',
    sellPick: 'Pick a part',
    sellPrice: 'Asking price (VOLTS)',
    fee: 'Grid fee (5%)',
    net: 'You receive',
    list: 'List for sale',
    listed: 'Listed. Buyers see it on the market now.',
    myTitle: 'My listings',
    selling: 'Selling',
    sold: 'Sold',
    bought: 'Bought',
    none: 'Nothing here yet.',
    cancelListing: 'Cancel listing',
    cancelled: 'Listing cancelled.',
    offline: 'The market is unreachable right now. Try again in a moment.',
    working: 'Working…',
  },
  challenge: {
    eyebrow: 'Weekly blueprint',
    title: 'Weekly Blueprint',
    subtitle: 'One target, one week. Build the cheapest rig that hits it at 100% stability.',
    back: 'Dashboard',
    endsIn: 'Ends in',
    ended: 'Closed',
    target: 'Target',
    perHour: 'hash/h',
    submissions: 'builds submitted',
    rewards: 'Prizes',
    rewardRank: ['1st', '2nd', '3rd'],
    builderTitle: 'Your build',
    builderHint: 'Tap an empty slot to add a part, a filled slot to remove it.',
    slotEmpty: 'Empty slot',
    slotAdd: 'Add part',
    pickerTitle: 'Pick a part',
    cost: 'Cost',
    hash: 'Hash',
    stability: 'Stability',
    heat: 'Heat',
    cooling: 'Cooling',
    draw: 'Draw',
    supply: 'Supply',
    meets: 'Meets the target',
    belowTarget: (need: number) => `Needs ${need} more hash/h`,
    unstable: 'Must run at 100% stability',
    submit: 'Submit build',
    resubmit: 'Update build',
    submitted: (rank: number) => `Submitted. You are ranked #${rank}.`,
    mine: 'Your entry',
    boardTitle: 'This week',
    rank: 'Rank',
    miner: 'Miner',
    build: 'Build',
    boardEmpty: 'No builds yet. Be the first on the board.',
    previousTitle: 'Last week',
    previousEmpty: 'No previous challenge.',
    winners: 'Winners',
    you: 'You',
    offline: 'The challenge board is unreachable right now.',
    clear: 'Clear',
    kinds: { CORE: 'Cores', COOLER: 'Cooling', PSU: 'Power', MODULE: 'Modules' },
  },
};

type Copy = typeof en;

const zh: Copy = {
  market: {
    segmentShop: '部件商店',
    segmentMarket: '玩家市场',
    title: '玩家市场',
    subtitle: '用 VOLTS 与其他矿工买卖自己的部件。每笔成交电网抽取 5%。',
    filterAll: '全部',
    sell: '出售部件',
    empty: '目前没有在售部件。挂出你自己的，或等下次事件后再来看看。',
    emptyFiltered: '目前没有该类型的在售部件。',
    daysLeft: '剩余',
    seller: '卖家',
    buy: '购买',
    yours: '你的',
    confirmTitle: '确认购买',
    confirmBody: '成交后部件立即转入你的矿机。交易不可撤销。',
    price: '价格',
    balance: '你的余额',
    after: '购买后',
    insufficient: 'VOLTS 不足，无法购买该部件。',
    confirm: '支付并安装',
    cancel: '取消',
    close: '关闭',
    boughtInstalled: (n: number) => `购买成功，已装入插槽 ${n}。`,
    boughtInventory: '购买成功。矿机插槽已满，部件已放入库存。',
    sellTitle: '出售部件',
    sellBody: '只有未安装且剩余超过三天的部件才能挂售。想出售请先从矿机上卸下。',
    sellNone: '库存中没有可出售的部件。请先在矿机页面卸下一个部件。',
    sellPick: '选择部件',
    sellPrice: '售价（VOLTS）',
    fee: '电网手续费（5%）',
    net: '你将收到',
    list: '挂单出售',
    listed: '已挂单，买家现在可以在市场看到。',
    myTitle: '我的挂单',
    selling: '出售中',
    sold: '已售出',
    bought: '已购买',
    none: '这里还是空的。',
    cancelListing: '撤销挂单',
    cancelled: '挂单已撤销。',
    offline: '暂时无法连接市场，请稍后重试。',
    working: '处理中…',
  },
  challenge: {
    eyebrow: '每周蓝图',
    title: '每周蓝图',
    subtitle: '一个目标，一周时间。用最低成本搭出在 100% 稳定度下达标的矿机。',
    back: '控制台',
    endsIn: '剩余',
    ended: '已结束',
    target: '目标',
    perHour: '算力/小时',
    submissions: '份配置已提交',
    rewards: '奖励',
    rewardRank: ['冠军', '亚军', '季军'],
    builderTitle: '你的配置',
    builderHint: '点击空插槽添加部件，点击已占用的插槽移除。',
    slotEmpty: '空插槽',
    slotAdd: '添加部件',
    pickerTitle: '选择部件',
    cost: '成本',
    hash: '算力',
    stability: '稳定度',
    heat: '热量',
    cooling: '散热',
    draw: '功耗',
    supply: '供电',
    meets: '已达标',
    belowTarget: (need: number) => `还差 ${need} 算力/小时`,
    unstable: '必须在 100% 稳定度下运行',
    submit: '提交配置',
    resubmit: '更新配置',
    submitted: (rank: number) => `已提交，你目前排名第 ${rank}。`,
    mine: '你的参赛配置',
    boardTitle: '本周',
    rank: '排名',
    miner: '矿工',
    build: '配置',
    boardEmpty: '还没有配置提交。抢占榜首吧。',
    previousTitle: '上周',
    previousEmpty: '没有上一期挑战。',
    winners: '获胜者',
    you: '你',
    offline: '暂时无法连接挑战榜。',
    clear: '清空',
    kinds: { CORE: '核心', COOLER: '散热', PSU: '供电', MODULE: '模块' },
  },
};

const ko: Copy = {
  market: {
    segmentShop: '부품 상점',
    segmentMarket: '플레이어 마켓',
    title: '플레이어 마켓',
    subtitle: 'VOLTS로 다른 채굴자와 보유 부품을 사고팝니다. 그리드가 판매액의 5%를 가져갑니다.',
    filterAll: '전체',
    sell: '부품 판매',
    empty: '지금 판매 중인 부품이 없습니다. 직접 등록하거나 다음 이벤트 후에 다시 확인하세요.',
    emptyFiltered: '해당 종류로 등록된 부품이 없습니다.',
    daysLeft: '남음',
    seller: '판매자',
    buy: '구매',
    yours: '내 것',
    confirmTitle: '구매 확인',
    confirmBody: '거래가 완료되는 즉시 부품이 리그로 옮겨집니다. 거래는 취소할 수 없습니다.',
    price: '가격',
    balance: '내 잔액',
    after: '구매 후',
    insufficient: 'VOLTS가 부족합니다.',
    confirm: '결제하고 장착',
    cancel: '취소',
    close: '닫기',
    boughtInstalled: (n: number) => `구매 완료. 슬롯 ${n}에 장착했습니다.`,
    boughtInventory: '구매 완료. 리그가 가득 차서 보관함으로 보냈습니다.',
    sellTitle: '부품 판매',
    sellBody:
      '장착되지 않았고 3일 넘게 남은 부품만 등록할 수 있습니다. 팔려면 먼저 리그에서 분리하세요.',
    sellNone: '판매할 부품이 보관함에 없습니다. 리그 페이지에서 먼저 분리하세요.',
    sellPick: '부품 선택',
    sellPrice: '희망가 (VOLTS)',
    fee: '그리드 수수료 (5%)',
    net: '실수령',
    list: '판매 등록',
    listed: '등록 완료. 이제 마켓에 노출됩니다.',
    myTitle: '내 등록',
    selling: '판매 중',
    sold: '판매됨',
    bought: '구매함',
    none: '아직 없습니다.',
    cancelListing: '등록 취소',
    cancelled: '등록을 취소했습니다.',
    offline: '지금은 마켓에 연결할 수 없습니다. 잠시 후 다시 시도하세요.',
    working: '처리 중…',
  },
  challenge: {
    eyebrow: '주간 블루프린트',
    title: '주간 블루프린트',
    subtitle: '한 주에 하나의 목표. 100% 안정도로 목표를 달성하는 가장 저렴한 리그를 만드세요.',
    back: '대시보드',
    endsIn: '종료까지',
    ended: '마감',
    target: '목표',
    perHour: '해시/시간',
    submissions: '개 빌드 제출됨',
    rewards: '상품',
    rewardRank: ['1위', '2위', '3위'],
    builderTitle: '내 빌드',
    builderHint: '빈 슬롯을 눌러 부품을 넣고, 채워진 슬롯을 눌러 뺍니다.',
    slotEmpty: '빈 슬롯',
    slotAdd: '부품 추가',
    pickerTitle: '부품 선택',
    cost: '비용',
    hash: '해시',
    stability: '안정도',
    heat: '발열',
    cooling: '냉각',
    draw: '전력 소비',
    supply: '전력 공급',
    meets: '목표 달성',
    belowTarget: (need: number) => `해시/시간 ${need} 부족`,
    unstable: '100% 안정도로 돌아가야 합니다',
    submit: '빌드 제출',
    resubmit: '빌드 수정',
    submitted: (rank: number) => `제출 완료. 현재 ${rank}위입니다.`,
    mine: '내 참가작',
    boardTitle: '이번 주',
    rank: '순위',
    miner: '채굴자',
    build: '빌드',
    boardEmpty: '아직 빌드가 없습니다. 첫 주자가 되세요.',
    previousTitle: '지난주',
    previousEmpty: '지난 챌린지가 없습니다.',
    winners: '수상자',
    you: '나',
    offline: '지금은 챌린지 보드에 연결할 수 없습니다.',
    clear: '비우기',
    kinds: { CORE: '코어', COOLER: '냉각', PSU: '전력', MODULE: '모듈' },
  },
};

const BY_LOCALE: Record<string, Copy> = { en, zh, ko };

/** Copy for the active locale; falls back to English. */
export function useMarket(): Copy {
  const locale = useLocale();
  return BY_LOCALE[locale] ?? en;
}

/** English copy, for anything that cannot call a hook. */
export const S = en;
