export type AdminTab =
  | 'dashboard'
  | 'users'
  | 'mining-engine'
  | 'boosters'
  | 'referrals'
  | 'withdrawals'
  | 'blockchain'
  | 'kyc'
  | 'marketplace'
  | 'tasks'
  | 'payments'
  | 'support'
  | 'cms'
  | 'reports'
  | 'security'
  | 'system';
